/* A packrat parser generated by PackCC 1.2.0 */

#ifndef PCC_INCLUDED__PGLC_H
#define PCC_INCLUDED__PGLC_H


#ifdef __cplusplus
extern "C" {
#endif

typedef struct pglc_context_tag pglc_context_t;

pglc_context_t *pglc_create(void *auxil);
int pglc_parse(pglc_context_t *ctx, int *ret);
void pglc_destroy(pglc_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* PCC_INCLUDED__PGLC_H */
