/* A packrat parser generated by PackCC 1.2.0 */

#ifndef PCC_INCLUDED__PYGL_H
#define PCC_INCLUDED__PYGL_H


#ifdef __cplusplus
extern "C" {
#endif

typedef struct pygl_context_tag pygl_context_t;

pygl_context_t *pygl_create(void *auxil);
int pygl_parse(pygl_context_t *ctx, int *ret);
void pygl_destroy(pygl_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* PCC_INCLUDED__PYGL_H */
